site_name: 🇵🇸 🍉❤️ JP For Palestine 
site_url: https://jpforpalestine.github.io/jpforpalestine

repo_url: https://github.com/jpforpalestine/jpforpalestine

theme:
  name: material
  logo: assets/logo.png
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  nav:
    - Home: index.md
    - Onboarding: onboarding/index.md
    - Resources: resources/index.md